name: Add Text Workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secret.CHECKOUT_TOKEN }}

      - name: Touch file
        run: touch temp.txt

      - name: Add text
        run: echo "hoge" > temp.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Add text
