name: Add Text Workflow
on:
  workflow_call:

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Touch file
        run: touch temp.txt

      - name: Add text
        run: echo "hoge" >> temp.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Add text
